Test suite passes
Several changes to user code required:

1. All references to metric tensor need to be changed from mesh->
   to a Coordinates pointer

2. StaggerGrids is now in the [mesh] section, rather than a global

3. The differencing methods are per-mesh, so rather than
   [ddx], [ddy], [ddz] these should be in [mesh:ddx], [mesh:ddy], [mesh:ddz]

diff --git a/examples/test-field/runtest b/examples/test-field/runtest
--- a/examples/test-field/runtest
+++ b/examples/test-field/runtest
@@ -1,7 +1,16 @@
 #!/bin/sh
 
-make
-./test_field
+echo "Running field test"
 
-exit $?
+make
+./test_field > test.log
+
+status=$?
+if [ $status -eq 0 ] ; then 
+  echo " => Test passed"
+else
+  echo " => Test Failed"
+fi
+
+exit $status
 
