test-options runtest update
Now checks return code. Prints log if the test fails,
and returns error code so that the test suite can detect
the failure.

Added a small README file

diff --git a/examples/test-options/runtest b/examples/test-options/runtest
--- a/examples/test-options/runtest
+++ b/examples/test-options/runtest
@@ -1,1 +1,14 @@
-make && ./test-options > log && echo "Success"
+make
+./test-options > log 
+
+# Check return code
+if [ $? -eq 0 ]; then
+  echo "Success"
+  exit 0
+else 
+  echo "Failed."
+  # print log so it's seen in Travis output
+  cat log
+  exit 1
+fi
+
