Put common parts of boutcore Field3D and Field2D into loops
Reduce code duplication.

diff --git a/tools/pylib/_boutcore_build/boutcpp.pxd.in b/tools/pylib/_boutcore_build/boutcpp.pxd.in
--- a/tools/pylib/_boutcore_build/boutcpp.pxd.in
+++ b/tools/pylib/_boutcore_build/boutcpp.pxd.in
@@ -6,11 +6,20 @@ from libcpp cimport bool
 from libcpp.string cimport string
 
 cimport resolve_enum as benum
+EOF
+for ftype in "Field3D" "Field2D"
+do
+  if [ $ftype = "Field3D" ]; then fheader="field3d";
+  elif [ $ftype = "Field2D" ]; then fheader="field2d";
+  else
+    echo "Error, unimplemented ftype"; exit 1
+  fi
+cat <<EOF
 
-cdef extern from "field3d.hxx":
-    cppclass Field3D:
-        Field3D(Mesh * mesh);
-        Field3D(const Field3D &)
+cdef extern from "$fheader.hxx":
+    cppclass $ftype:
+        $ftype(Mesh * mesh);
+        $ftype(const $ftype &)
         double & operator()(int,int,int)
         int getNx()
         int getNy()
@@ -24,38 +33,16 @@ cdef extern from "field3d.hxx":
 EOF
 for f in sqrt exp log sin cos abs
 do
-    echo "    Field3D $f(Field3D)"
+    echo "    $ftype $f($ftype)"
 done
 cat <<EOF
-    double max(Field3D)
-    double min(Field3D)
-    Field3D pow(Field3D,double)
-    Field3D & ddt(Field3D)
-
-cdef extern from "field2d.hxx":
-    cppclass Field2D:
-        Field2D(Mesh * mesh);
-        Field2D(const Field2D &)
-        double & operator()(int,int)
-        int getNx()
-        int getNy()
-        int getNz()
-        bool isAllocated()
-        void setLocation(benum.CELL_LOC)
-        benum.CELL_LOC getLocation()
-        void applyBoundary(const string bndry)
-        void applyBoundary()
-        void applyBoundary(double t)
+    double max($ftype)
+    double min($ftype)
+    $ftype pow($ftype,double)
+    $ftype & ddt($ftype)
 EOF
-for f in sqrt exp log sin cos abs
-do
-    echo "    Field2D $f(Field2D)"
 done
 cat <<EOF
-    double max(Field2D)
-    double min(Field2D)
-    Field2D pow(Field2D,double)
-    Field2D & ddt(Field2D)
 
 cdef extern from "bout/mesh.hxx":
     cppclass Mesh:
diff --git a/tools/pylib/_boutcore_build/helper.cxx.in b/tools/pylib/_boutcore_build/helper.cxx.in
--- a/tools/pylib/_boutcore_build/helper.cxx.in
+++ b/tools/pylib/_boutcore_build/helper.cxx.in
@@ -4,23 +4,100 @@ cat <<EOF
 #include <derivs.hxx>
 #include <difops.hxx>
 #include <invert_laplace.hxx>
+EOF
+for ftype in "Field3D" "Field2D"
+do
+  if [ $ftype = "Field3D" ]; then fdd="f3d";
+  elif [ $ftype = "Field2D" ]; then fdd="f2d";
+  else
+    echo "Error, unimplemented ftype"; exit 1
+  fi
+cat <<EOF
 
-void c_set_f3d_all(Field3D * f3d, const double * data){
+void c_set_${fdd}_all($ftype * f, const double * data){
   int j=0;
-  f3d->allocate();
-  for (auto i : (*f3d)){
-    (*f3d)[i]=data[j++];
+  f->allocate();
+  for (auto i : (*f)){
+    (*f)[i]=data[j++];
   }
 }
-void c_set_f3d_all_(Field3D * f3d, const double data){
-  (*f3d)=data;
+
+void c_set_${fdd}_all_($ftype * f, const double data){
+  (*f)=data;
 }
-void c_get_f3d_all(const Field3D * f3d, double * data){
+
+void c_get_${fdd}_all(const $ftype * f, double * data){
   int j=0;
-  for (auto i : (*f3d)){
-    data[j++]=(*f3d)[i];
+  for (auto i : (*f)){
+    data[j++]=(*f)[i];
   }
 }
+
+int getNx( $ftype * a){
+  return a->getNx();
+}
+
+int getNy( $ftype * a){
+  return a->getNy();
+}
+
+int getNz( $ftype * a){
+  return a->getNz();
+}
+EOF
+
+for f in "add:+" "mul:*" "truediv:/" "div:/" "sub:-"
+do
+    n=${f%:*}
+    o=${f#*:}
+    cat <<EOF
+
+$ftype * f$n($ftype*a,$ftype*b){
+  $ftype * r=new $ftype(*a);
+  *r $o= *b;
+  return r;
+}
+
+$ftype * f$n($ftype*a,double b){
+  $ftype * r=new $ftype(*a);
+  *r $o= b;
+  return r;
+}
+
+$ftype * f$n(double b,$ftype*a){
+  return new $ftype(b $o *a);
+}
+
+void fi$n($ftype*a,$ftype*b){
+  *a $o= *b;
+}
+
+void fi$n($ftype*a,double b){
+  *a $o= b;
+}
+EOF
+if [ $ftype = "Field3D" ]; then
+cat <<EOF
+
+Field3D * f$n(Field3D*a,Field2D*b){
+  Field3D * r=new Field3D(*a);
+  *r $o= *b;
+  return r;
+}
+
+Field3D * f$n(Field2D*a,Field3D*b){
+  return new Field3D(*b $o *a);
+}
+
+void fi$n(Field3D*a,Field2D*b){
+  *a $o= *b;
+}
+EOF
+fi
+done
+
+done
+cat <<EOF
 
 void c_get_f3d_part(const Field3D * f3d, double * data,int xs,int xe, int dx,int ys,int ye, int dy,int zs,int ze, int dz){
   int j=0;
@@ -55,23 +132,6 @@ void c_set_f3d_part_(Field3D * f3d, const double data,int xs,int xe, int dx,int 
   }
 }
 
-void c_set_f2d_all(Field2D * f2d, const double * data){
-  int j=0;
-  f2d->allocate();
-  for (auto i : (*f2d)){
-    (*f2d)[i]=data[j++];
-  }
-}
-void c_set_f2d_all_(Field2D * f2d, const double data){
-  (*f2d)=data;
-}
-void c_get_f2d_all(const Field2D * f2d, double * data){
-  int j=0;
-  for (auto i : (*f2d)){
-    data[j++]=(*f2d)[i];
-  }
-}
-
 void c_get_f2d_part(const Field2D * f2d, double * data,int xs,int xe, int dx,int ys,int ye, int dy){
   int j=0;
   for (int x=xs;x!=xe;x+=dx){
@@ -97,86 +157,6 @@ void c_set_f2d_part_(Field2D * f2d, const double data,int xs,int xe, int dx,int 
       (*f2d)(x,y)=data;
     }
   }
-}
-
-EOF
-
-for f in "add:+" "mul:*" "truediv:/" "div:/" "sub:-"
-do
-    n=${f%:*}
-    o=${f#*:}
-    cat <<EOF
-Field3D * f$n( Field3D*a,Field3D*b){
-  Field3D * r=new Field3D(*a);
-  *r $o= *b;
-  return r;
-}
-
-Field3D * f$n( Field3D*a,Field2D*b){
-  Field3D * r=new Field3D(*a);
-  *r $o= *b;
-  return r;
-}
-
-Field3D * f$n( Field2D*a,Field3D*b){
-  return new Field3D(*b $o *a);
-}
-
-Field3D * f$n( Field3D*a,double b){
-  Field3D * r=new Field3D(*a);
-  *r $o= b;
-  return r;
-}
-
-Field3D * f$n( double b,Field3D*a){
-  return new Field3D(b $o *a);
-}
-
-void fi$n( Field3D*a,Field3D*b){
-  *a $o= *b;
-}
-void fi$n( Field3D*a,Field2D*b){
-  *a $o= *b;
-}
-void fi$n( Field3D*a,double b){
-  *a $o= b;
-}
-
-Field2D * f$n( Field2D*a,Field2D*b){
-  Field2D * r=new Field2D(*a);
-  *r $o= *b;
-  return r;
-}
-
-Field2D * f$n( Field2D*a,double b){
-  Field2D * r=new Field2D(*a);
-  *r $o= b;
-  return r;
-}
-
-Field2D * f$n( double b,Field2D*a){
-  return new Field2D(b $o *a);
-}
-
-void fi$n( Field2D*a,Field2D*b){
-  *a $o= *b;
-}
-void fi$n( Field2D*a,double b){
-  *a $o= b;
-}
-EOF
-done
-
-cat <<EOF
-int getNx( Field3D * a){
-  return a->getNx();
-}
-int getNy( Field3D * a){
-  //printf("%d\n",a->getNy());
-  return a->getNy();
-}
-int getNz( Field3D * a){
-  return a->getNz();
 }
 
 Mesh * c_get_global_mesh(){
